# Use C-a instead of C-b 
set -g prefix C-a
bind-key C-a last-window

# Dracula Colours
# background_color '#282a36'
# current_line_color '#44475a'
# foreground_color '#f8f8f2'
# comment_color '#6272a4'
# cyan '#8be9fd'
# green '#50fa7b'
# orange '#ffb86c'
# pink '#ff79c6'
# purple '#bd93f9', colour141
# red '#ff5555'
# yellow '#f1fa8c'

set -g default-terminal "screen-256color"

# pane border
set -g pane-border-style fg='#bd93f9'
set -g pane-active-border-style fg='#ff79c6'

# message text
set -g message-style bg='#44475a',fg='#8be9fd'

# clock
set-window-option -g clock-mode-colour '#50fa7b' 

# status line
set -g status-style bg='#44475a',fg='#bd93f9'
set-window-option -g window-status-style fg='#bd93f9',bg=default
set-window-option -g window-status-current-style fg='#ff79c6',bg='#282a36'
set -g status-interval 1
set -g status-justify centre
set -g status-left-length 80
set -g status-right-length 140
set -g status-left ':)'

# status right
set -g status-right '#[fg=green,bg=default,bright]#(tmux-mem-cpu-load) '
set -ga status-right '#[fg=red,dim,bg=default]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") '
set -ga status-right '#[fg=white,bg=default]%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d'

# set window split
bind-key v split-window -h
bind-key b split-window

# fix pane_current_path on new window and splits
unbind c
bind c new-window -c "#{pane_current_path}"
unbind b
bind b split-window -v -c "#{pane_current_path}"
unbind v
bind v split-window -h -c "#{pane_current_path}"

# Start numbering at 1
set -g base-index 1

# set default-shell path/to/zsh

# Allows for faster key repetition
set -s escape-time 0

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Allows us to use C-a a <command> to send commands to a TMUX session inside 
# another TMUX session
bind-key a send-prefix

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# set to main-horizontal, 66% height for main pane
bind m run-shell "~/.tmux/scripts/resize-adaptable.sh -l main-horizontal -p 66"
# Same thing for verical layouts
bind M run-shell "~/.tmux/scripts/resize-adaptable.sh -l main-vertical -p 50"

bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# auto window rename
# set-window-option -g automatic-rename

# Vi copypaste mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# utf8 status bar
# set -g status-utf8 on

# mouse mode 
set -g mouse off
